services:
  cache:
    image: redis:7.2.5-alpine
    command: redis-server --save 15 1 --loglevel warning
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data
    restart: always
  api:
    container_name: int-ladbrokes
    build:
      context: .
      dockerfile: Dockerfile.local
    depends_on:
      - cache
    volumes:
      - ./:/src
    environment:
      - LOG_LEVEL=debug
      - STORAGE_ADDRESS=cache:6379
    ports:
      - '8080:8080'
volumes:
  cache:
