services:
  cache:
    image: redis:6.2-alpine
    command: redis-server --save 15 1 --loglevel warning
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data
    restart: always
  api:
    container_name: int-ladbrokes
    build:
      context: .
      dockerfile: Dockerfile.local
    depends_on:
      - cache
    volumes:
      - ./:/src
    environment:
      - LOG_LEVEL=debug
    ports:
      - '3000:3000'
volumes:
  cache:
