services:
  cache:
    image: redis:7.2.5-alpine
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server --loglevel warning"]
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data
    restart: always
  app:
    container_name: int-ladbrokes
    build:
      context: .
      dockerfile: Dockerfile.local
    depends_on:
      - cache
    volumes:
      - ./:/src
    environment:
      - LOG_LEVEL=debug
      - STORAGE_ADDRESS=cache:6379
    ports:
      - '8080:8080'
volumes:
  cache:
